# Generated by Django 4.0.4 on 2022-09-08 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('article_name', models.CharField(max_length=150)),
                ('about', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('date_born', models.DateField()),
                ('date_died', models.DateField()),
                ('nationality', models.CharField(max_length=150)),
                ('known_for', models.CharField(max_length=255)),
                ('notable_work', models.CharField(max_length=255)),
            ],
        ),
    ]
