# Generated by Django 4.0.4 on 2022-09-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='designed_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='articles',
            name='developer',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='articles',
            name='dimensions',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='articles',
            name='lecture_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='articles',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='articles',
            name='medium',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='articles',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='articles',
            name='year',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date_born',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date_died',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='known_for',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='nationality',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='articles',
            name='notable_work',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
