# Generated by Django 4.1.1 on 2022-09-08 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_date_born_alter_article_date_died_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_born',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2022)]),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_died',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2022)]),
        ),
        migrations.AlterField(
            model_name='article',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
